blank_issues_enabled: true
contact_links:
 - name: SolarHub Frontend (Recommended)
   url: https://space-gen.github.io/solarhub/
   about: Annotate data via the GUI (Frontend)

 - name: SolarHub - Aurora Documentation
     url: https://space-gen.github.io/aurora/
     about: Learn more about the Aurora annotation pipeline.
